# each line is a individual package. "#" comments out a line.

# base system
base
sudo
ex-vi-compat
less
git
plocate
linux-rt
mkinitcpio
amd-ucode
linux-firmware-mediatek
linux-firmware-amdgpu
linux-firmware-realtek
bash-completion
btrfs-progs
efibootmgr
tmux
iptables
dosfstools 
firewalld
fail2ban
tinyssh
lm_sensors
snapper
snap-pac
lsof
smartmontools
reflector
pacman-contrib
pipewire-pulse
wireplumber
pipewire-jack
pipewire-v4l2
pipewire-audio
pipewire-roc
pipewire-alsa
realtime-privileges
rtkit
rsync
atop
ncdu
python
nginx
incus
umoci
cdrtools
apparmor
thin-provisioning-tools
lvm2
fwupd
python-dbus
python-gobject
udisks2
