# each line is a individual service. "#" comments out a line.
systemd-networkd
systemd-resolved
reflector
lm_sensors
gpm
incus
sudo_logsrvd
systemd-oomd
udisks2
paccache.timer
reflector.timer
fstrim.timer
pacman-filesdb-refresh.timer
rsyncd
sensord
apparmor
auditd
audit-rules
dbus-broker
dropbear
fail2ban
shadow
smartd
systemd-timesyncd
systemd-time-wait-sync
ufw
systemd-hostnamed
uuid
reflector.timer
shadow
shadow.timer
